[package]
name = 'core-packages/symbol'
description = 'https://github.com/grilme99/CorePackages'
version = '1.1.0'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
